// Build examples/zxspectrum.js — the one prebuilt browser bundle.
//
// Bundles the browser entry (which imports @zx-vibes/machine + the render/keyboard
// helpers) into a single classic IIFE exposing `window.ZXSpectrum`, with the 48K
// ROM embedded as base64. A classic script + embedded ROM is what lets the demos
// run from a double-clicked file:// page — browsers block ES-module and fetch of
// local files, but a plain <script src> and inline data are fine.

import esbuild from 'esbuild';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, '..', 'zxspectrum.js');

// 1) Embed the ROM as base64 in a generated module the bundle imports.
const rom = readFileSync(join(HERE, '48k.rom'));
if (rom.length !== 16384) throw new Error(`48K ROM must be 16384 bytes, got ${rom.length}`);
writeFileSync(
  join(HERE, 'rom-data.generated.mjs'),
  `// Generated by build.mjs — the 48K ROM (c) Amstrad plc, redistributed by permission (see ../NOTICE).\nexport const ROM_BASE64 = ${JSON.stringify(rom.toString('base64'))};\n`,
);

// 2) Bundle to a single IIFE global.
const result = await esbuild.build({
  entryPoints: [join(HERE, 'browser-entry.mjs')],
  bundle: true,
  format: 'iife',
  globalName: 'ZXSpectrum',
  target: ['es2020'],
  legalComments: 'none',
  banner: { js: '/* ZX Spectrum emulator bundle — @zx-vibes/machine. ROM (c) Amstrad plc, by permission. */' },
  outfile: OUT,
  metafile: true,
});

const bytes = readFileSync(OUT).length;
console.log(`Built ${OUT} (${(bytes / 1024).toFixed(0)} KB, ROM embedded).`);
if (result.warnings.length) console.warn(`${result.warnings.length} esbuild warning(s).`);
