// Scaffold services — `new` / `init` / `clean` (cli.md CLI-PROD-NEW-001 +
// CLI-PROD-OUT-NEW-001, CLI-PROD-INIT-001 + CLI-PROD-EDGE-004, CLI-PROD-CLEAN-001;
// config-schema.md CFG-PROD-*; knowledge-pack.md KP-PROD-CONTENT-PLAYBOOK-001).
//
// These are the project-bootstrap verbs of the loop:
//   - `new <name>`  scaffolds a fresh project DIRECTORY that `zxs verify` PASSES out
//                   of the box (zx.config.json + an entry .asm that assembles and runs
//                   clean + a green tests/ smoke suite + the agent playbook).
//   - `init`        lays the same toolkit contract INTO an existing directory,
//                   non-destructively (idempotent; never clobbers a present file
//                   unless `--force`), reporting what it created vs skipped.
//   - `clean`       removes the generated artifacts (`build/` + `.zxs/`) so the next
//                   attempt starts clean; an absent dir is a success, not an error.
//
// W5 boundary (the clean-room seal): this slice emits a MINIMAL valid project — NOT
// the rich starter templates. The elaborate `game`/`platformer` starter contract (a
// lib/, a Makefile, the full knowledge pack, an installable package.json) belongs to
// `create-zx-vibes` + `starters/` (W5, which owns conformance row SCAFFOLD-VERIFY-001).
// `new` accepts `--template <game|platformer>` and records it as informational config
// metadata (CFG-PROD-FIELD-TEMPLATE-001), but the generated bytes are the same minimal
// project; the template-specific content is W5's job. Likewise the full knowledge pack
// is installed by `zxs setup` (Slice 11) — here we ship only the minimal agent playbook
// the scaffold itself mandates (KP-PROD-CONTENT-PLAYBOOK-001), not the whole pack.

import { existsSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { basename, dirname, isAbsolute, relative, resolve } from 'node:path';
import type { Command } from 'commander';
import {
  DEFAULT_ASSEMBLER,
  DEFAULT_ORG,
  DEFAULT_OUT_DIR,
  resolveConfig,
} from '../config/config.js';
import { successEnvelope, userError, type SuccessEnvelope } from '../output/envelope.js';
import { ZXS_DIR } from '../state/persist.js';
import type { CommandContext } from '../registry.js';

/** The default `--template` (CLI-PROD-NEW-001). */
export const DEFAULT_TEMPLATE = 'game';
/** The published package name recorded in a generated `zx.config.json` `toolkit` field. */
export const TOOLKIT_ID = '@zx-vibes/toolkit';
/** The conventional entry path a generated project configures (config-schema.md example). */
export const SCAFFOLD_ENTRY = 'src/main.asm';

// --- the minimal project content (clean-room: derived from this toolkit's own
//     proven-green verify/test fixtures, never from any oracle/W5 starter) --------

/**
 * The entry program: a HALT-synced 48K game loop. It assembles with the embedded
 * `@zx-vibes/asm`, sets the border (a port-0xFE write), enables IM 1 interrupts, and
 * idles in `halt`/`jr` — so a fresh 300-frame `run` reports `status:"ok"` with
 * `haltSynced:true` (no hang). This is exactly the shape `zxs verify` needs to pass.
 */
export const ENTRY_ASM = [
  '; Minimal zx-vibes entry point — a HALT-synced ZX Spectrum 48K game loop.',
  '; Assembles with the embedded @zx-vibes/asm and runs clean under `zxs verify`.',
  '        ORG 0x8000',
  'start:',
  '        ld sp, 0xFF00      ; a safe stack high in RAM',
  '        ld a, 2            ; border = red (also proves a port-0xFE write)',
  '        out (0xFE), a',
  '        ld a, 0x2A         ; a token byte...',
  '        ld (0x9000), a     ; ...stored so memEquals @0x9000 == 0x2A is provable',
  '        im 1               ; interrupt mode 1 (the ROM 50 Hz frame interrupt)',
  '        ei                 ; enable interrupts so HALT releases each frame',
  'main:',
  '        halt               ; wait for the frame interrupt (HALT-synced loop)',
  '        jr main',
  '',
].join('\n');

/**
 * The green smoke suite: one self-contained spec proving the toolchain end-to-end —
 * the program runs to `status:"ok"`, the loop is HALT-synced, and the border is the
 * expected colour. Its `smoke.asm` lives beside the spec in `tests/`, so the proof
 * stays green regardless of the project's own sources (the sandbox roots at the
 * project root, so a spec may also build `../src/…`, but this one deliberately does not).
 */
export const SMOKE_TEST_JSON = `${JSON.stringify(
  {
    build: 'smoke.asm',
    frames: 30,
    assert: [
      { type: 'status', equals: 'ok' },
      { type: 'haltSynced', equals: true },
      { type: 'borderColor', equals: 2 },
    ],
  },
  null,
  2,
)}\n`;

/** Ignore the generated artifacts `clean` removes. */
export const GITIGNORE = ['build/', '.zxs/', ''].join('\n');

/**
 * The minimal agent playbook (KP-PROD-CONTENT-PLAYBOOK-001) written to both `AGENTS.md`
 * and `CLAUDE.md`. It encodes the one operating rule — *never report success without
 * running and looking* — and points at the loop. The FULL knowledge pack (skills +
 * reference + recipes) is installed separately by `zxs setup` (cli.md CLI-PROD-SETUP-001).
 * Prose is Incidental (CLI-PROD-FREE-001 / KP-PROD-FREE-001).
 */
export const PLAYBOOK = `# Agent Playbook — zx-vibes (ZX Spectrum 48K)

This project is built, run, and **proven** with the \`zxs\` toolkit
(\`@zx-vibes/toolkit\`). One rule governs everything:

> **Never report success without running and looking.**

A program that assembles is not a program that works. Always close the loop:

1. \`zxs build --json\` — assemble \`src/main.asm\` into \`build/\`.
2. \`zxs run --json\` — run it fresh for 300 frames under the hang watchdog.
3. \`zxs screen --text\` — read the screen back (cheap eyes).
4. \`zxs verify --json\` — the single acceptance gate: build -> run -> screenshot -> tests.

\`zxs verify\` exits \`0\` only when the build succeeds, the run does **not** hang, and
every spec under \`tests/\` passes. Treat any non-zero exit as "not done yet".

Useful observation/debug commands: \`zxs regs\`, \`zxs mem read <addr>\`,
\`zxs disasm <spec>\`, \`zxs trace\`, \`zxs test tests/\`. Remove generated artifacts
with \`zxs clean\`.

This is a minimal starting playbook. Install the full knowledge pack (skills,
reference docs, recipes) with \`zxs setup --agent <codex|claude>\`.
`;

// --- envelopes --------------------------------------------------------------

/** `new` success envelope (no rich JSON contract beyond CLI-PROD-OUT-NEW-001 exit codes). */
export type NewEnvelope = SuccessEnvelope<{
  name: string;
  /** Portable (relative, `/`-separated) path to the created project directory. */
  dir: string;
  template: string;
  /** Project-relative paths of the files written (sorted). */
  files: string[];
  next: string[];
}>;

/** `init` success envelope — reports created vs preserved files (CLI-PROD-EDGE-004). */
export type InitEnvelope = SuccessEnvelope<{
  /** Files written (project-relative, sorted). */
  created: string[];
  /** Files left untouched because they already existed (project-relative, sorted). */
  skipped: string[];
  force: boolean;
  next: string[];
}>;

/** `clean` success envelope — the exact `{ ok, stage:"clean", removed:[…] }` shape (CLI-PROD-CLEAN-001). */
export type CleanEnvelope = SuccessEnvelope<{
  removed: string[];
}>;

// --- options ----------------------------------------------------------------

export interface NewOptions {
  /** The project (directory) name to create. */
  name: string;
  /** Project root the directory is created under (defaults to `process.cwd()`). */
  cwd?: string | undefined;
  /** `--template <game|platformer>` (default `game`); recorded as config metadata. */
  template?: string | undefined;
}

export interface InitOptions {
  /** The existing directory to onboard (defaults to `process.cwd()`). */
  cwd?: string | undefined;
  /** `--force`: overwrite managed files instead of preserving present ones. */
  force?: boolean | undefined;
}

export interface CleanOptions {
  /** The project root to clean (defaults to `process.cwd()`). */
  cwd?: string | undefined;
}

// --- new --------------------------------------------------------------------

/**
 * Scaffold a fresh project directory (CLI-PROD-NEW-001). Validates the name, fails
 * (USER_ERROR, exit 1) if the target directory already exists (CLI-PROD-OUT-NEW-001),
 * then writes the minimal verify-passing project. Returns the `new` envelope.
 */
export function runNew(options: NewOptions): NewEnvelope {
  const cwd = resolve(options.cwd ?? process.cwd());
  const name = options.name;
  validateProjectName(name);

  const template = (options.template ?? DEFAULT_TEMPLATE).trim() || DEFAULT_TEMPLATE;
  const dir = resolve(cwd, name);
  if (existsSync(dir)) {
    throw userError(`Cannot create project "${name}": the target directory already exists`, 'new');
  }

  const files = writeFiles(dir, newProjectFiles(name, template), false).created;
  return successEnvelope('new', {
    name,
    dir: portableRel(dir, cwd),
    template,
    files,
    next: [`cd ${name}`, 'zxs verify --json'],
  });
}

/** The file set a fresh project ships (relative path -> content). */
function newProjectFiles(name: string, template: string): Array<[string, string]> {
  return [
    ['zx.config.json', configJson({ name, template })],
    [SCAFFOLD_ENTRY, ENTRY_ASM],
    ['tests/smoke.asm', ENTRY_ASM],
    ['tests/smoke.test.json', SMOKE_TEST_JSON],
    ['AGENTS.md', PLAYBOOK],
    ['CLAUDE.md', PLAYBOOK],
    ['.gitignore', GITIGNORE],
  ];
}

/**
 * Validate a project name (CLI-PROD-OUT-NEW-001: an invalid name exits 1). The exact
 * rule is Incidental (the spec only says "invalid"); we require a single safe directory
 * segment — letters, digits, dot, hyphen, underscore — which rejects empty names, `.`/
 * `..`, path separators, whitespace, and filesystem-reserved/control characters.
 */
function validateProjectName(name: string): void {
  if (name.trim() === '') {
    throw userError('Invalid project name: the name must not be empty', 'new');
  }
  if (name === '.' || name === '..') {
    throw userError(`Invalid project name: "${name}"`, 'new');
  }
  if (!/^[A-Za-z0-9._-]+$/.test(name)) {
    throw userError(
      'Invalid project name: use letters, digits, ".", "-" or "_" (no spaces or path separators)',
      'new',
    );
  }
}

// --- init -------------------------------------------------------------------

/**
 * Scaffold the toolkit contract into an existing directory (CLI-PROD-INIT-001):
 * `zx.config.json`, a `tests/` smoke suite, and the `AGENTS.md`/`CLAUDE.md` playbook.
 * Non-destructive (CLI-PROD-EDGE-004): a present file is preserved (reported under
 * `skipped`) unless `--force`. Never fails on present files; idempotent.
 */
export function runInit(options: InitOptions = {}): InitEnvelope {
  const cwd = resolve(options.cwd ?? process.cwd());
  const force = options.force ?? false;
  const name = basename(cwd) || 'zx-project';

  const { created, skipped } = writeFiles(cwd, initProjectFiles(name), force);
  return successEnvelope('init', {
    created,
    skipped,
    force,
    next: ['zxs test tests/ --json', 'zxs verify --json'],
  });
}

/**
 * The toolkit-contract file set `init` lays down (CLI-PROD-INIT-001). NB: no
 * `src/main.asm` — `init` onboards a repo that supplies its own entry; it only adds the
 * contract + the self-contained smoke suite (which proves the toolchain on its own).
 */
function initProjectFiles(name: string): Array<[string, string]> {
  return [
    ['zx.config.json', configJson({ name })],
    ['tests/smoke.asm', ENTRY_ASM],
    ['tests/smoke.test.json', SMOKE_TEST_JSON],
    ['AGENTS.md', PLAYBOOK],
    ['CLAUDE.md', PLAYBOOK],
  ];
}

// --- clean ------------------------------------------------------------------

/**
 * Remove the generated artifacts (CLI-PROD-CLEAN-001): the configured output directory
 * (default `build/`) and the `.zxs/` session/cache dir. Reports the paths actually
 * removed; an absent directory is silently skipped (absence is a success, not an error).
 */
export function runClean(options: CleanOptions = {}): CleanEnvelope {
  const cwd = resolve(options.cwd ?? process.cwd());
  const removed: string[] = [];
  for (const target of cleanTargets(cwd)) {
    const abs = resolve(cwd, target);
    if (existsSync(abs)) {
      rmSync(abs, { recursive: true, force: true });
      removed.push(portableRel(abs, cwd));
    }
  }
  removed.sort();
  return successEnvelope('clean', { removed });
}

/**
 * The directories `clean` targets: the resolved `outDir` (default `build`) plus `.zxs`.
 * Config resolution is best-effort — an invalid `zx.config.json` must not block cleaning
 * `.zxs/`, so we fall back to the default output directory.
 */
function cleanTargets(cwd: string): string[] {
  let outDir = DEFAULT_OUT_DIR;
  try {
    outDir = resolveConfig({ cwd }).outDir;
  } catch {
    outDir = DEFAULT_OUT_DIR;
  }
  return [...new Set([outDir, ZXS_DIR])];
}

// --- shared helpers ---------------------------------------------------------

/** Build a `zx.config.json` body (CFG-PROD-* defaults; `template` is optional metadata). */
function configJson(meta: { name: string; template?: string }): string {
  const config: Record<string, string> = {
    name: meta.name,
    entry: SCAFFOLD_ENTRY,
    org: DEFAULT_ORG,
    assembler: DEFAULT_ASSEMBLER,
    outDir: DEFAULT_OUT_DIR,
  };
  if (meta.template !== undefined) config.template = meta.template;
  config.toolkit = TOOLKIT_ID;
  return `${JSON.stringify(config, null, 2)}\n`;
}

/**
 * Write a file set under `root`. With `force` false, a present file is left untouched
 * and reported under `skipped`; otherwise it is (over)written and reported under
 * `created`. Returns both lists, project-relative and sorted.
 */
function writeFiles(
  root: string,
  entries: Array<[string, string]>,
  force: boolean,
): { created: string[]; skipped: string[] } {
  const created: string[] = [];
  const skipped: string[] = [];
  for (const [rel, content] of entries) {
    const abs = resolve(root, rel);
    if (!force && existsSync(abs)) {
      skipped.push(rel);
      continue;
    }
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, content, 'utf8');
    created.push(rel);
  }
  created.sort();
  skipped.sort();
  return { created, skipped };
}

/** Make a path stable + portable: relative to `cwd` when inside it, `/`-separated. */
function portableRel(path: string, cwd: string): string {
  const abs = resolve(path);
  const rel = relative(cwd, abs);
  const chosen = rel === '' || rel.startsWith('..') || isAbsolute(rel) ? abs : rel;
  return chosen.split('\\').join('/');
}

// --- CLI wiring -------------------------------------------------------------

/** The `new` command handler: maps the CLI context onto {@link runNew}. */
export function newCommand(context: CommandContext): NewEnvelope {
  const options = context.options as { template?: string };
  // `--no-install` is accepted for surface-compatibility (CLI-PROD-NEW-001) but is a
  // no-op: the minimal project carries no dependency manifest to install (the installable
  // package contract is W5's rich starter). Nothing to thread through here.
  return runNew({
    name: context.args[0] ?? '',
    cwd: process.cwd(),
    template: options.template,
  });
}

/** Declare the `new` command's argument + flags (CLI-PROD-NEW-001). */
export function configureNewCommand(command: Command): void {
  command
    .description('Scaffold a fresh ZX Spectrum 48K project')
    .argument('<name>', 'project directory name to create')
    .option('--template <name>', 'starter template (game|platformer; default game)')
    .option('--no-install', 'skip dependency install (no-op for the minimal scaffold)')
    .option('--json', 'emit a single machine-readable JSON envelope');
}

/** The `init` command handler: maps the CLI context onto {@link runInit}. */
export function initCommand(context: CommandContext): InitEnvelope {
  const options = context.options as { force?: boolean };
  return runInit({ cwd: process.cwd(), force: options.force });
}

/** Declare the `init` command's flags (CLI-PROD-INIT-001). */
export function configureInitCommand(command: Command): void {
  command
    .description('Scaffold the toolkit contract into an existing directory')
    .option('--force', 'overwrite managed files instead of preserving present ones')
    .option('--json', 'emit a single machine-readable JSON envelope');
}

/** The `clean` command handler: maps the CLI context onto {@link runClean}. */
export function cleanCommand(_context: CommandContext): CleanEnvelope {
  return runClean({ cwd: process.cwd() });
}

/** Declare the `clean` command's flags (CLI-PROD-CLEAN-001). */
export function configureCleanCommand(command: Command): void {
  command
    .description('Remove generated artifacts (build/ and .zxs/)')
    .option('--json', 'emit a single machine-readable JSON envelope');
}

// Each handler returns a success Envelope (failures are thrown as a CliError the
// dispatcher renders); these assertions document the registry contract.
const _newCheck: (c: CommandContext) => NewEnvelope = newCommand;
const _initCheck: (c: CommandContext) => InitEnvelope = initCommand;
const _cleanCheck: (c: CommandContext) => CleanEnvelope = cleanCommand;
void _newCheck;
void _initCheck;
void _cleanCheck;
